name: jjagro_balanca_avicola
description: "JJ Agro - Balança Avícola Pro: Aplicativo móvel para pesagem avícola industrial com BLE e ESP32"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Biblioteca Bluetooth Serial Clássico mantida para Flutter moderno
  lutter_bluetooth_serial_plus: ^0.5.6
  # Banco de Dados Local Offline (SQLite)
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # Geração de Planilhas Excel (.xlsx)
  excel: ^4.0.3

  # Compartilhamento via WhatsApp, E-mail e Arquivos
  share_plus: ^10.1.2
  path_provider: ^2.1.4

  # Gerenciamento de Estado Reativo
  provider: ^6.1.2

  # Formatação de Datas
  intl: ^0.19.0

  # Gráficos Zootécnicos
  fl_chart: ^0.69.0

  # Tipografia Moderna
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
