name: Gerar APK Balança Avícola

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x'
          channel: 'stable'

      - name: Criar esqueleto de projeto Flutter caso falte
        run: |
          if [ ! -f "android/build.gradle" ] && [ ! -f "android/build.gradle.kts" ]; then
            flutter create . --project-name balanca_avicola_pro --org com.jjagro.balanca
          fi

      - name: Baixar dependências
        run: flutter pub get

      - name: Compilar APK (Release)
        run: flutter build apk --release

      - name: Disponibilizar APK para download
        uses: actions/upload-artifact@v4
        with:
          name: Balanca-Avicola-Pro-Release
          path: build/app/outputs/flutter-apk/app-release.apk
